import "~/styles/globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";

import { GeistSans } from "geist/font/sans";
import {
  FooterAdmin,
  NavSideBarAdmin,
} from "~/app/_components/adminComponents";

export const metadata: Metadata = {
  title: {
    template: "Travel Town Holidays | Admin | %s ",
    default: "Travel Town Holidays | Admin",
  },
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="dark overflow-x-hidden bg-gray-200">
        <TRPCReactProvider>
          <NavSideBarAdmin />
          {children}
          <FooterAdmin />
          <Toaster />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
